mindvalley/mv-opentelemetry

- OWNERS
- README.md
Signed-off-by: Abdulla Mulail Mohamed <mulailmohamed@gmail.com>
> feat: update readme/add owners

- CONTRIBUTING.md
- LICENSE.md
Signed-off-by: Maciej Szlosarczyk <maciej@mindvalley.com>
> Add LICENSE and CONTRIBUTING documents

- OWNERS
- lib/mv_opentelemetry/absinthe.ex
- lib/mv_opentelemetry/ecto.ex
- lib/mv_opentelemetry/live_view.ex
- lib/mv_opentelemetry/plug.ex
- test/mv_opentelemetry/absinthe_test.exs
- test/mv_opentelemetry/ecto_test.exs
- test/mv_opentelemetry/live_view_test.exs
- test/mv_opentelemetry/plug_test.exs
Signed-off-by: Maciej Szlosarczyk <maciej@mindvalley.com>
> Add support for maps in query and path params

- lib/mv_opentelemetry.ex
- lib/mv_opentelemetry/absinthe.ex
- lib/mv_opentelemetry/ecto.ex
- lib/mv_opentelemetry/plug.ex
- test/mv_opentelemetry/absinthe_test.exs
- test/mv_opentelemetry/plug_test.exs
Fixes #12, at least for the places where it is possible and can be done.
> Update params to standard

- README.md
- lib/mv_opentelemetry.ex
- lib/mv_opentelemetry/span_tracer.ex
- mix.exs
* Remove unused version attribute from span tracer
* Update all version mentions to 1.0.0
Signed-off-by: Maciej Szlosarczyk <maciej@mindvalley.com>
> Pre-release preparations

- jenkins/jenkinsfile-ci
Signed-off-by: Abdulla Mulail Mohamed <mulailmohamed@gmail.com>
> feat(jenkins-ci): update formatting

- jenkins/jenkinsfile-ci
Signed-off-by: Isaac Chong <isaac@flexnode.com>
> chore(IE-413): remove use of job cacher plugin in jenkinsfile-ci

- README.md
Signed-off-by: Anton Satin <satinantond@gmail.com>
> Updated readme installation instructions

- lib/mv_opentelemetry/absinthe.ex
- mv_opentelemetry_harness/lib/mv_opentelemetry_harness_web/router.ex
- test/mv_opentelemetry/absinthe_test.exs
https://hexdocs.pm/absinthe/complexity-analysis.html
> Add complexity to absinthe events

- lib/mv_opentelemetry/absinthe.ex
I'm not sure exactly why it's nil, will take a look at the actual data and then adjust tests accordingly.
> Handle nil current operation for complexity

- mix.exs
> Add absinthe as an optional dependency

- .github/workflows/gh-action-sast-ci.yaml
- README.md
This PR will:
- Configure Sobelow for Code Scanning
> feat(codeql): configure sobelow

- lib/mv_opentelemetry/finch.ex
> Add exception handling to Finch telemetry

- OWNERS
- mix.exs
> Update version, add Fadhil to reviewers

- lib/mv_opentelemetry/tesla.ex
In this PR, we group tesla requests together by attaching the spans to the parent context.
We additionally upcase the method names as reported by Tesla to keep in line with existing processors in this library.
> refactor: attach request spans to parent context

- .known_dialyzer_warnings
- mix.exs
- test/mv_opentelemetry/tesla_test.exs
> Cleanup Tesla test code

- .github/workflows/gh-action-ci.yaml
This PR will add GH CI workflow to run CI tests using Github Actions
> IE-1102 feat(gh-actions): add GH CI workflow

- lib/mv_opentelemetry/absinthe.ex
- test/mv_opentelemetry/absinthe_test.exs
This adds ability to see variables that were passed along with query in
absinthe spans. This functionality must be explicitly enabled in the
config.
> Add variables to absinthe spans

- .github/workflows/gh-action-ci.yaml
- .github/workflows/gh-action-sast-ci.yaml
This PR will:
- update github actions to use latest versions for gh actions
> chore(github): update actions

- .github/workflows/gh-action-ci.yaml
> Do not run the coverage action on 'main' branch
